# Generated by Django 4.2.7 on 2024-04-12 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BattleSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('threshold', models.FloatField(default=0.6)),
                ('gold', models.IntegerField(db_index=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twich_video_id', models.IntegerField(db_index=True, unique=True)),
                ('time', models.DateTimeField(db_index=True)),
                ('language', models.IntegerField(db_index=True, help_text='1 = en, 2 = jp')),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('result', models.IntegerField(db_index=True, help_text='不明ならnull,勝ちなら1,負けなら2', null=True)),
                ('battle_set', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='buildcrawler.battleset')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('mixed_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mixed_item', to='buildcrawler.item')),
                ('result_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='result_item', to='buildcrawler.item')),
            ],
        ),
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('player', models.IntegerField(db_index=True, help_text='不明ならnull,配信者なら1,対戦相手なら2', null=True)),
                ('accept', models.BooleanField(help_text='初期値がnull, 認証してたらtrue, rejectならfalse', null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='buildcrawler.item')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='buildcrawler.round')),
            ],
        ),
        migrations.AddField(
            model_name='battleset',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='buildcrawler.video'),
        ),
        migrations.AddConstraint(
            model_name='build',
            constraint=models.UniqueConstraint(fields=('round', 'item', 'player'), name='build_round_item_player'),
        ),
    ]
